services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    ports:
      - '4317:4317'
      - '4318:4318'
      - '55680:55680' # OTLP gRPC
      - '8889:8889' # Porta para metricas
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - '--config=/etc/otel-collector-config.yaml'
    networks:
      - otel-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - otel-network

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - '14250:14250'
    networks:
      - otel-network

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.2
    ports:
      - '3000:3000'
    networks:
      - otel-network

  poc-app:
    container_name: poc-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3001
    ports:
      - '3001:3001'
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
