# Permite setar configurações globais
global:
  scrape_interval: 10s # Com essa configuração o prometheus vai buscar os dados a cada 10s

# Configurações do "scraper"
scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
